# The URL the site will be built for
base_url = "https://matthewperry.engineer"
title = "Matthew Perry"

description = "A personal site and portfolio featuring technology ramblings."

compile_sass = false
build_search_index = false

[markdown]
highlight_code = false

[extra]

# Header navigation
nav = [
    { name = "Home", path = "/"},
    { name = "Tracking", path = "/tracking"},
    { name = "Projects", path = "/projects"}
]
