# The URL the site will be built for
base_url = "https://matthewperry.engineer"
title = "Matthew Perry's Site"

compile_sass = false
build_search_index = false

[markdown]
highlight_code = false

[extra]

# Header navigation
nav = [
    { name = "Home", path = "/"}
]